In [1]:
import nltk 
from chefboost import Chefboost as chef
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\riaju\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
cdf=pd.read_excel('Spam_comment.xlsx')
cdf

Comment  Value
0              সব চোর একসাথে ...দেশটা কেমনে উন্নতি করবে      0
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক      1
2                       বাল ছিড়তে পারে নি আর এখন ছিড়বো       1
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়      1
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর      0
...                                                 ...    ...
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...      1
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা      1
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে      1
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়।      1
1099                          জামাই আদর কারে করা হচ্ছে?      1

[1100 rows x 2 columns]

In [4]:
cdf.to_csv('output.csv','r', encoding='utf-8')
cdf

Comment  Value
0              সব চোর একসাথে ...দেশটা কেমনে উন্নতি করবে      0
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক      1
2                       বাল ছিড়তে পারে নি আর এখন ছিড়বো       1
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়      1
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর      0
...                                                 ...    ...
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...      1
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা      1
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে      1
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়।      1
1099                          জামাই আদর কারে করা হচ্ছে?      1

[1100 rows x 2 columns]

In [5]:
#remove punctuation
import re
import emoji
def remove_punc(text):
    whitespace = re.compile(u"[\s\u0020\u00a0\u1680\u180e\u202f\u205f\u3000\u2000-\u200a]+", re.UNICODE)
    bangla_fullstop = u"\u0964"
    punctSeq   = u"['\"“”‘’]+|[.?!,…]+|[:;]+"
    punc = u"[৷–()—,$%^&*+={}\[\]:\"|\'\~`<>/,€¦!?½£¶™¼©⅐⅑⅒⅓⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞⅟↉¤¿º;-]+"
    text= whitespace.sub(" ",text).strip()
    text= re.sub(punctSeq, " ", text)
    text = re.sub(bangla_fullstop, " ",text)
    text = re.sub(punc, " ", text)
    text = re.sub('\w*\d\w*', " ", text)
    text = re.sub(emoji.get_emoji_regexp(), "", text)
    return text

In [6]:
cdf['Clean']= cdf['Comment'].apply(lambda x: remove_punc(x))
cdf

Comment  Value  \
0              সব চোর একসাথে ...দেশটা কেমনে উন্নতি করবে      0   
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক      1   
2                       বাল ছিড়তে পারে নি আর এখন ছিড়বো       1   
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়      1   
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর      0   
...                                                 ...    ...   
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...      1   
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা      1   
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে      1   
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়।      1   
1099                          জামাই আদর কারে করা হচ্ছে?      1   

                                                  Clean  
0                সব চোর একসাথে  দেশটা কেমনে উন্নতি করবে  
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক  
2                        বাল ছিড়তে পারে নি আর এখন ছিড়বো  
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়  
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর  
...                                                 ...  
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...  
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা  
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে  
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়   
1099                          জামাই আদর কারে করা হচ্ছে   

[1100 rows x 3 columns]

In [7]:
#Tokenize
cdf['tokenized_sents'] = cdf.apply(lambda row: nltk.word_tokenize(row['Clean']), axis=1)
cdf

Comment  Value  \
0              সব চোর একসাথে ...দেশটা কেমনে উন্নতি করবে      0   
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক      1   
2                       বাল ছিড়তে পারে নি আর এখন ছিড়বো       1   
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়      1   
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর      0   
...                                                 ...    ...   
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...      1   
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা      1   
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে      1   
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়।      1   
1099                          জামাই আদর কারে করা হচ্ছে?      1   

                                                  Clean  \
0                সব চোর একসাথে  দেশটা কেমনে উন্নতি করবে   
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক   
2                        বাল ছিড়তে পারে নি আর এখন ছিড়বো   
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়   
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর   
...                                                 ...   
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...   
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা   
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে   
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়    
1099                          জামাই আদর কারে করা হচ্ছে    

                                        tokenized_sents  
0         [সব, চোর, একসাথে, দেশটা, কেমনে, উন্নতি, করবে]  
1     [মাগী, কে, করোনা, ভাইরাস, এর, রোগীর, চোদা, খাও...  
2                [বাল, ছিড়তে, পারে, নি, আর, এখন, ছিড়বো]  
3      [চিকিৎসা, না, দিয়ে, বিছানা, গরম, করে, মনে, হয়]  
4     [শালা, স্বাস্থ্য, খাতে, এত, দুর্নীতি, শালা, সব...  
...                                                 ...  
1095  [আমরা, সিঙ্গাপুর, হয়ে, গেছি, ইনশাআল্লাহ, কোন,...  
1096  [কলা, খেয়ে, খেয়ে, ফিগারটা, দারুন, বানাইসে, সাব...  
1097              [রিমান্ডে, দুধ, খাওয়াবো, পুলিশ, গোরে]  
1098   [চেহারা, দেখে, ডাক্তার, নয়, অন্য, কিছু, মনে, হয়]  
1099                     [জামাই, আদর, কারে, করা, হচ্ছে]  

[1100 rows x 4 columns]

In [8]:
stopwords="অতএব আমারেও টা ভাই নাম কই গুলো আপনাদের BBQ অন\u200d্যায়ের অন\u200d্যায় \u200c\u200c smart Pro Subscribe try YouTube   অথচ অথবা অনুযায়ী অনেক অনেকে অনেকেই অন্তত অন্য যায়নি অবধি অবশ্য অর্থাত আই আগামী আগে আগেই আছে আজ আদ্যভাগে আপনার আপনি আবার আমরা আমাকে আমাদের আমার আমি আর আরও ই ইত্যাদি ইহা উচিত উত্তর উনি উপর উপরে এ এঁদের এঁরা এই একই একটি একবার একে এক এখন এখনও এখানে এখানেই এটা এটাই এটি এত এতটাই এতে এদের এব এবং এবার এমন এমনকী এমনি এর এরা এল এস এসে ঐ ও ওঁদের ওঁর ওঁরা ওই ওকে ওখানে ওদের ওর ওরা কখনও কত কবে কমনে কয়েক কয়েকটি করছে করছেন করতে করবে করবেন করলে করলেন করা করাই করায় করার করি করিতে করিয়া করিয়ে করে করেই করেছিলেন করেছে করেছেন করেন কাউকে কাছ কাছে কাজ কাজে কারও কারণ কি কিংবা কিছু কিছুই কিন্তু কী কে কেউ কেউই কেখা কেন কোটি কোন কোনও কোনো ক্ষেত্রে কয়েক খুব গিয়ে গিয়েছে গিয়ে গুলি গেছে গেল গেলে গোটা চলে চান চায় চার চালু চেয়ে চেষ্টা ছাড়া ছাড়াও ছিল ছিলেন জন জনকে জনের জন্য জন্যওজে জানতে জানা জানানো জানায় জানিয়ে জানিয়েছে জে জ্নজন টি ঠিক তখন তত তথা তবু তবে তা তাঁকে তাঁদের তাঁর তাঁরা তাঁহারা তাই তাও তাকে তাতে তাদের তার তারপর তারা তারৈ তাহলে তাহা তাহাতে তাহার তিন তিনি তিনিও তুমি তুলে তেমন তো তোমার থাকবে থাকবেন থাকা থাকায় থাকে থাকে থেকে থেকেই থেকেও দিকে দিতে দিন দিয়ে দিয়েছে দিয়েছেন দিলেন দুই দুটি দুটো দেওয়া দেওয়ার দেওয়া দেখতে দেখা দেখে দেন দেয় দ্বারা ধরা ধরে ধামার নতুন নয় না নাই নাকি নগদ নানা নিজে নিজেই নিজেদের নিজের নিতে নিয়ে নেই নেওয়া নেওয়ার  নয় পক্ষে পর পরে পরেই পরেও পর্যন্ত পাওয়া পাচ পারি পারে পারেন  পেয়ে প্রতি প্রথম প্রভৃতি প্রাথমিক প্রায় ফলে ফিরে ফের বক্তব্য বদলে বন বরং বলতে বলল বললেন বলা বলে বলেছেন বলেন বসে বহু বা বাদে বার বি বিনা বিভিন্ন বিশেষ বিষয়টি বেশ বেশি ব্যবহার ব্যাপারে ভাবে ভাবেই মতো মতোই মধ্যভাগে মধ্যে মধ্যেই মধ্যেও মনে মাত্র মাধ্যমে মোট মোটেই যখন যত যতটা যথেষ্ট যদি যদিও যা যাঁর যাঁরা যাওয়া যাওয়ার যাওয়া যাকে যাচ্ছে যাতে যাদের যান যাবে যায় যার যারা যিনি যে যেখানে যেতে যেন যেমন রকম রয়েছে রাখা রেখে লক্ষ শুধু শুরু সঙ্গে সঙ্গেও সব সবার সমস্ত সম্প্রতি সহ সহিত সাধারণ সামনে সি সুতরাং সে সেই সেখান সেখানে সেটা সেটাই সেটাও সেটি স্পষ্ট স্বয়ং হইতে হইবে হইয়া হওয়া হওয়ায় হওয়ার হচ্ছে হত হতে হতেই হন হবে হবেন হয় হয়তো হয়নি হয়ে হয়েই হয়েছিল হয়েছে হয়েছেন হল হলে হলেই হলেও হলো হাজার হিসাবে হৈলে হোক হয় অবশ্য অনেক  নকে অনেকেই অন্তত অথবা অথচ অর্থাত অন্য আজ আছে আপনার আপনি আবার আমরা আমাকে আমাদের আমার আমি আরও আর আগে আগেই আই অতএব আগামী অবধি অনুযায়ী আদ্যভাগে এই এভাবেই একই এসেছে একে একটি এখন এখনও এখানে এখানেই এটি এটা এটাই এতটাই এবং একবার এবার এদের এঁদের এমন এমনকী এল এর এরা এঁরা এস এত এতে এসে একে এ ঐ  ই ইহা ইত্যাদি উনি উপর উপরে উচিত ও ওই ওর ওরা ওঁর ওঁরা ওকে ওদের ওঁদের ওখানে কত কবে করতে কয়েক কয়েকটি করবে করলেন  করার কারও করা  করি করিয়ে করার করাই করলে করলেন করিতে  করিয়া করেছিলেন করছে করছেন করেছেন করেছে  করেন করবেন করায় করে করেই কাছ কাছে কাজে কারণ কিছু কিছুই  কিন্তু কিংবা কি কী  কেউ  কেউই কাউকে কেন  কে  কোনও  কোনো কোন  কখনও ক্ষেত্রে খুব গুলি গিয়ে গিয়েছে গেছে  গেল গেলে গোটা চলে ছাড়া ছাড়াও ছিলেন  ছিল জন্য জানা  ঠিক তিনি তিন তিনিও তখন  তবে  তবু তাঁদের  তাঁহারা তাঁরা  তাঁর তাঁকে তাই তেমন তাকে  তাহা তাহাতে তাহার তাদের  তারপর  তারা  তারৈ তার তাহলে তিনি তা তাও তাতে তো  তত তুমি  তোমার  তথা থাকে থাকা থাকায় থেকে থেকেও থাকবে থাকেন থাকবেন থেকেই  দিকে  দিতে  দিয়ে দিয়েছে দিয়েছেন দিলেন  দুটি দুটো দেয় দেওয়া দেওয়ার দেখা  দেখে দেখতে দ্বারা  ধরে ধরা নয়  নানা  না নাকি নাগাদ নিতে নিজে নিজেই নিজের নিজেদের নিয়ে নেওয়া নেওয়ার নেই নাই পক্ষে পর্যন্ত পাওয়া  পারেন  পারি পারে পরে পরেই পরেও পর পেয়ে  প্রতি  প্রভৃতি  প্রায় ফের ফলে  ফিরে ব্যবহার  বলতে  বললেন বলেছেন বলল  বলা  বলেন  বলে  বহু বসে বার বা বিনা বরং ব লে বাদে বার বিশেষ বিভিন্ন বিষয়টি  ব্যবহার ব্যাপারে ভাবে ভাবেই মধ্যে মধ্যেই মধ্যেও মধ্যভাগে মাধ্যমে মাত্র  মতো মতোই মোটেই যখন  যদি  যদিও যাবে যায় যাকে যাওয়া যাওয়ার যত যতটা যা যার যারা যাঁর যাঁরা যাদের যান যাচ্ছে  যেতে যাতে  যেন  যেমন  যেখানে যিনি যে রেখে সংখ্যা স্ত্রী রাখা রয়েছে রকম শুধু  সঙ্গে সঙ্গেও সমস্ত সব সবার সহ  সুতরাং  সহিত সেই সেটা সেটি সেটাই সেটাও সম্প্রতি সেখান সেখানে  সে স্পষ্ট  স্বয়ং হইতে  হইবে  হৈলে হইয়া  হচ্ছে  হত হতে  হতেই হবে  হবেন হয়েছিল  হয়েছে হয়েছেন হয়ে হয়নি হয় হয়েই হয়তো হল হলে হলেই হলেও হলো হিসাবে হওয়া হওয়ার হওয়ায় হন হোক জন জনকে জনের জানতে জানায় জানিয়ে জানানো জানিয়েছে জন্য বেশ দেন তুলে ছিলেন চান চায় চেয়ে মোট যথেষ্ট টি "
doc=stopwords.split()
doc

['অতএব',
 'আমারেও',
 'টা',
 'ভাই',
 'নাম',
 'কই',
 'গুলো',
 'আপনাদের',
 'BBQ',
 'অন\u200d্যায়ের',
 'অন\u200d্যায়',
 '\u200c\u200c',
 'smart',
 'Pro',
 'Subscribe',
 'try',
 'YouTube',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'যায়নি',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',

In [9]:
def reomve_stopwrds(text):
    text=[word for word in text if word not in doc]
    return text

In [10]:
cdf['cmt_r_wrds']= cdf['tokenized_sents'].apply(lambda x: reomve_stopwrds(x))
cdf

Comment  Value  \
0              সব চোর একসাথে ...দেশটা কেমনে উন্নতি করবে      0   
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক      1   
2                       বাল ছিড়তে পারে নি আর এখন ছিড়বো       1   
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়      1   
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর      0   
...                                                 ...    ...   
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...      1   
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা      1   
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে      1   
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়।      1   
1099                          জামাই আদর কারে করা হচ্ছে?      1   

                                                  Clean  \
0                সব চোর একসাথে  দেশটা কেমনে উন্নতি করবে   
1        মাগী কে করোনা ভাইরাস এর রোগীর চোদা খাওয়ানো হোক   
2                        বাল ছিড়তে পারে নি আর এখন ছিড়বো   
3               চিকিৎসা না দিয়ে বিছানা গরম করে মনে হয়   
4           শালা স্বাস্থ্য খাতে এত দুর্নীতি শালা সব চোর   
...                                                 ...   
1095  আমরা সিঙ্গাপুর হয়ে গেছি ইনশাআল্লাহ কোন সমস্যা...   
1096        কলা খেয়ে খেয়ে ফিগারটা দারুন বানাইসে সাবরিনা   
1097                    রিমান্ডে দুধ খাওয়াবো পুলিশ গোরে   
1098           চেহারা দেখে ডাক্তার নয় অন্য কিছু মনে হয়    
1099                          জামাই আদর কারে করা হচ্ছে    

                                        tokenized_sents  \
0         [সব, চোর, একসাথে, দেশটা, কেমনে, উন্নতি, করবে]   
1     [মাগী, কে, করোনা, ভাইরাস, এর, রোগীর, চোদা, খাও...   
2                [বাল, ছিড়তে, পারে, নি, আর, এখন, ছিড়বো]   
3      [চিকিৎসা, না, দিয়ে, বিছানা, গরম, করে, মনে, হয়]   
4     [শালা, স্বাস্থ্য, খাতে, এত, দুর্নীতি, শালা, সব...   
...                                                 ...   
1095  [আমরা, সিঙ্গাপুর, হয়ে, গেছি, ইনশাআল্লাহ, কোন,...   
1096  [কলা, খেয়ে, খেয়ে, ফিগারটা, দারুন, বানাইসে, সাব...   
1097              [রিমান্ডে, দুধ, খাওয়াবো, পুলিশ, গোরে]   
1098   [চেহারা, দেখে, ডাক্তার, নয়, অন্য, কিছু, মনে, হয়]   
1099                     [জামাই, আদর, কারে, করা, হচ্ছে]   

                                             cmt_r_wrds  
0                   [চোর, একসাথে, দেশটা, কেমনে, উন্নতি]  
1           [মাগী, করোনা, ভাইরাস, রোগীর, চোদা, খাওয়ানো]  
2                               [বাল, ছিড়তে, নি, ছিড়বো]  
3                                [চিকিৎসা, বিছানা, গরম]  
4          [শালা, স্বাস্থ্য, খাতে, দুর্নীতি, শালা, চোর]  
...                                                 ...  
1095              [সিঙ্গাপুর, গেছি, ইনশাআল্লাহ, সমস্যা]  
1096  [কলা, খেয়ে, খেয়ে, ফিগারটা, দারুন, বানাইসে, সাব...  
1097              [রিমান্ডে, দুধ, খাওয়াবো, পুলিশ, গোরে]  
1098                                  [চেহারা, ডাক্তার]  
1099                                 [জামাই, আদর, কারে]  

[1100 rows x 5 columns]

In [12]:
x=cdf.iloc[:, 4]
y=cdf.iloc[:, 1]

In [17]:
#import gensim
#from gensim.models import Word2Vec
#model1 = gensim.models.Word2Vec(x, size=100, window=5, min_count=1, workers=4)

In [25]:
#vec=model1.wv['জামাই']-model1.wv['আদর']+model1.wv['শালা']

In [26]:
#model1.wv.most_similar([vec])

[('জামাই', 0.6229996085166931),
 ('শালা', 0.5804205536842346),
 ('মান', 0.34886226058006287),
 ('সারসে', 0.3410566449165344),
 ('দেশটাকে', 0.31950175762176514),
 ('চালাক', 0.31916987895965576),
 ('পদ', 0.3119138479232788),
 ('ডা', 0.30703508853912354),
 ('অন্তরে', 0.304962158203125),
 ('ফেইস', 0.3008311986923218)]

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(tokenizer=lambda doc1: doc1, lowercase=False)
X = vec.fit_transform(x).toarray()
print(X.shape)
X
#print(vec.get_feature_names())

#from sklearn.feature_extraction.text import CountVectorizer 
#vectorizer =CountVectorizer(tokenizer=lambda doc: doc, lowercase=False).fit_transform(z)
#X=vectorizer.toarray()
#X[50]

(1100, 2814)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state = 10)

# DT

In [36]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(max_depth=50)#criterion='entropy',max_depth=50
dtree.fit(x_train,y_train)
y_pred=dtree.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [37]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.8454545454545455

# MLP

In [52]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=50, activation='relu',max_iter=100)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
y_pred

c:\users\riaju\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [53]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.8515151515151516

# LDA

In [54]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
lda.fit_transform(x_train, y_train)
y_pred = lda.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [55]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.8484848484848485

# NB

In [56]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [57]:
from sklearn.metrics import classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 18,  24],
       [ 70, 218]], dtype=int64)

In [58]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.7151515151515152

In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.20      0.43      0.28        42
           1       0.90      0.76      0.82       288

    accuracy                           0.72       330
   macro avg       0.55      0.59      0.55       330
weighted avg       0.81      0.72      0.75       330



# SVM

In [60]:
from sklearn import svm
SVM = svm.SVC(kernel='linear')
#C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=True, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None
SVM.fit(x_train, y_train)
# predict the labels on validation dataset
y_pred = SVM.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [61]:
from sklearn.metrics import classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[  6,  36],
       [  5, 283]], dtype=int64)

In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.55      0.14      0.23        42
           1       0.89      0.98      0.93       288

    accuracy                           0.88       330
   macro avg       0.72      0.56      0.58       330
weighted avg       0.84      0.88      0.84       330



In [63]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.8757575757575757

# ADa

In [76]:
#Create adaboost classifer object
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=100,learning_rate=1)
model = abc.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [77]:
from sklearn.metrics import classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[  5,  37],
       [  8, 280]], dtype=int64)

In [78]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, y_pred)
acc

0.8636363636363636

In [79]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.38      0.12      0.18        42
           1       0.88      0.97      0.93       288

    accuracy                           0.86       330
   macro avg       0.63      0.55      0.55       330
weighted avg       0.82      0.86      0.83       330



In [10]:
prediction= [(4268968909, [955398943, 2529072432,
1600413013])]

Truth= [(4268968909, [955398943])]
import ml_metrics as metrics
x=metrics.mapk(Truth,prediction,7)
x

0.5

In [11]:
import ml_metrics as metrics
x=metrics.mapk(Truth,prediction,2)
x

0.5